export { default as Nav } from './Nav/Nav'
export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as Content } from './Content/Content'
export { default as ContentForm } from './ContentForm/ContentForm'
export { default as ContentFormCelular } from './ContentFormCelular/ContentFormCelular'